Update of morphman to anki version 2.1.35
kaegi/MorphMan pull request #178
Opened 2020-11-07 23:07 UTC by dmgerman

- updated settings to use new anki API
- added support to export morphs to sqlite3
- added optional support to ignore narrow parentheses (not available in GUI yet)
- added profiling code (disabled by default)
- print and log the name of the mecab being used

2020-11-07 23:24 UTC, ianki commented on morph/readability.py
> +                        log_fp.write('Morph: ' + str(m) + '\n')
Let's drop this change, since it slows down processing.

2020-11-07 23:34 UTC, ianki commented on morph/morphemes.py
> +            save_db_locations(cur, db, tname)
Are you sure you want to overwrite 'tname'?

Why not just use: save_db_locations(cur, db, 'locations') ?

2020-11-07 23:36 UTC, ianki commented on morph/main.py
> +#                db.execute('select ivl, type from cards where nid = :nid', nid=nid)]
nit: just delete the commented line

2020-11-07 23:36 UTC, ianki commented on morph/main.py
> +#        'update notes set tags=?, flds=?, sfld=?, csum=?, mod=?, usn=? where id=?', ds)
nit: just delete the line

2020-11-07 23:36 UTC, ianki commented on morph/main.py
> +#        'update cards set due=?, mod=?, usn=? where id=?', ds)
nit: same here

2020-11-07 23:38 UTC, ianki commented on morph/preferences.py
> +#    original = mw.col.conf['addons']['morphman'].copy()
nit: remove commented lines

2020-11-07 23:38 UTC, ianki commented on morph/preferences.py
> +    #conf = mw.col.conf['addons']['morphman']
nit: remove commented lines

2020-11-07 23:43 UTC, ianki commented on morph/morphemes.py
> -        if square_brackets_regex.search(expression):
I think the 'if' conditions were added intentionally to reduce new string object allocations if they weren't needed.

2020-11-07 23:44 UTC, ianki commented on morph/morphemes.py
> +round_brackets_regex = re.compile(r'[\(（][^）\)]+[）\)]')
I'd prefer to keep these as separate options.

2020-11-07 23:44 UTC, ianki commented on morph/morphemes.py
> -        if square_brackets_regex.search(expression):
nvm, I see you made that change in the following patch.

2020-11-07 23:45 UTC, ianki commented on morph/config.py
> +    #Option_IgnoreSlimRoundBracketContents : False,
Should these lines _be_ commented out?

2020-11-07 23:46 UTC, ianki requested changes
I left a few comments, please take a look.

2020-11-07 23:48 UTC, ianki commented on morph/morphemes.py
> +round_brackets_regex = re.compile(r'[\(（][^）\)]+[）\)]')
nvm, I see this was done in the next patch.

2020-11-07 23:49 UTC, dmgerman commented
Thanks. I'll clean up the changes. Some issues are because I wrote commits that overrode previous commits. I tried to squash almost everything related. Let me create a new pull request where I address your comments. And clean up the old code.

about the IgnoreBrackets options. I'll profile it and see what is better. I assume speed is more important than memory.

2020-11-07 23:58 UTC, joestrong commented
I have done some PRs recently that helps improve some features for at least 2.1.26 too, including the brackets feature, batch play etc. if anyone wants to take a look?

Not sure who the maintainers are here, who can merge etc.

2020-11-08 00:14 UTC, ianki commented
> I have done some PRs recently that helps improve some features for at least 2.1.26 too, including the brackets feature, batch play etc. if anyone wants to take a look?
> 
> Not sure who the maintainers are here, who can merge etc.

I can push to the main repo, if you want to send PRs.

2020-11-08 00:17 UTC, joestrong commented
> > I have done some PRs recently that helps improve some features for at least 2.1.26 too, including the brackets feature, batch play etc. if anyone wants to take a look?
> > 
> > Not sure who the maintainers are here, who can merge etc.
> 
> I can push to the main repo, if you want to send PRs.

Yeah, the most recent 4 PRs before this one are me! Also this one fixes a recent bug: https://github.com/kaegi/MorphMan/pull/174

2020-11-08 02:12 UTC, closed without merging

2020-11-08 04:05 UTC, ianki commented
joestrong has already added round bracket support & tests to https://github.com/kaegi/MorphMan/pull/175.

Should we just merge that?