V3 compatible, Recalc improved, progress bars fixed
kaegi/MorphMan pull request #296
Opened 2023-08-10 09:44 UTC by mortii

2023-08-11 17:06 UTC, landonepps requested changes
Overall looks good, I appreciate the attention to detail like renaming variables.
I'm happy to merge it if you can address the linter warnings.

Also, the `master` branch is outdated. The latest version on AnkiWeb is using the `qt6-migration` branch. I'll merge your changes into that branch after it gets merged to master.

2023-08-12 11:05 UTC, mortii commented on morph/main.py
> +        mw.taskman.run_on_main(lambda: mw.progress.update(value=i))
aah, nice!

2023-08-12 12:25 UTC, mortii commented
I fixed the lint errors and I rebased onto qt6-migration

2023-08-12 12:35 UTC, mortii commented
hold on, a very a sneaky error appeared that needs to be fixed

2023-08-12 13:01 UTC, mortii commented
there was an invisible input parameter after removing a lambda, but it's fixed now.

2023-08-12 21:04 UTC, mortii commented
Also this should probably be placed in the ankiweb description until we get a proper wiki/guide (next on my todo-lis):

> NB! If the deck you are studying has sub-decks then new cards will by default only be gathered from the first sub-deck until it is empty before looking for new cards in the next sub-deck. If you instead want to get new i+1 cards from all sub-decks do the following:
> 1. Activate the v3 scheduler: Tools -> Review -> Scheduler -> V3 scheduler
> 2. Deck that has sub-decks: Deck options -> Display Order -> New card gather order -> Ascending position

The writing is kinda clunky, feel free to improve it in whatever way you see fit , lol.

2023-08-13 02:59 UTC, merged

2023-08-13 03:02 UTC, landonepps commented
Looks good to me, thanks for all the work you did here.
And I appreciate the AnkiWeb note, I'll be sure to add it.

2023-08-15 16:12 UTC, PrentissLiu commented
Thank you so much for your work. I am the version of QT5. I tried to modify: 
readability_ui.py and readability_settings_ui.py : 

> from PyQt6 import QtCore, QtGui, QtWidgets
to 
> from PyQt5 import QtCore, QtGui, QtWidgets

it works!

2023-08-17 05:09 UTC, landonepps commented
Awesome, I really appreciate the report!
Both of my computers are arm-based Macs, which don't support Qt5, making it quite annoying to test.

If this is really all that's needed, I should be able to modify the UI generation code to replace these imports with the aqt version and have full backwards compatibility.